on: [push]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Generate docs
    steps:
    - uses: actions/checkout@v2

    - name: Use make-docs-action
      id: make-docs
      uses: michalinacienciala/make-docs-action@main
      # with:
      #   workDir: './test'

    # Use the output from the `hello` step
    # - name: Get the output time
    #   run: echo "The time was ${{ steps.hello.outputs.time }}"